ALTER TABLE refresh_tokens ALTER COLUMN id TYPE INTEGER;

ALTER TABLE refresh_tokens ALTER COLUMN user_id TYPE INTEGER;

ALTER TABLE contacts ALTER COLUMN user_id TYPE INTEGER;

ALTER TABLE user_roles ALTER COLUMN user_id TYPE INTEGER;

ALTER TABLE user_roles ALTER COLUMN role_id TYPE INTEGER;

